name: Python flask application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Static analysis
      run: |
        pip install flake8
        flake8 --max-line-length=150 --ignore=E266 *.py project/*.py project/*/routes.py
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov-report term-missing --cov=project
